### ISSUE TITLE
Error install in windows

### ISSUE THREAD

**Issue by Moriand** [JanMarvin/readspss#16]
install using 
`devtools::install_git("https://github.com/JanMarvin/readspss.git")`

error obtain for Rtools, using R version 3.2.2 and  R-devel 4.0
```r
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Downloading git repo https://github.com/JanMarvin/readspss.git
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Error: Failed to install 'unknown package' from Git:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

**Comment by JanMarvin** [comment]
Hi @Moriand , thanks for the report, though I am not entirely sure what the problem is. To build readspss from git on Windows you require Rtools which is a compiler set. See https://cran.r-project.org/bin/windows/Rtools/

If you want to install only a binary package, have a look at my draft repo see the Readme for instructions.
